name: Java Build

on: [push, pull_request]

env:
  AWS_DEFAULT_REGION: us-west-2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
      - name: Codecov
        uses: codecov/codecov-action@v5.1.1
